drop function acs_interface__new(varchar,varchar,boolean,text,timestamp,integer,varchar);
drop function acs_interface__delete(integer);
drop function acs_interface__delete(varchar,varchar);
drop function acs_interface__assoc_obj_type_with_interface (varchar,varchar,varchar,varchar);
drop function acs_interface__remove_obj_type_impl (varchar,varchar,varchar);
drop function acs_interface__get_interface_id (varchar,varchar);
drop function acs_interface__add_method (varchar,varchar,varchar,varchar,varchar,text);
drop function acs_interface__add_param_to_method (integer,varchar,varchar,integer,text,text,boolean,boolean);
drop function acs_interface__remove_method (integer);
drop function acs_interface__remove_param_from_method (integer,integer);
drop function acs_interface__object_type_implement_p (varchar,varchar,varchar);
drop function acs_interface__object_id_implement_p (varchar,varchar,varchar);
drop function acs_interface__obj_provide_implement (varchar,varchar,varchar);
